/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//
//import java.awt.GridLayout;

import javax.swing.*;
import java.awt.*;

//import javax.swing.JButton;
//import javax.swing.JPanel;

/**
 *
 * @author Kanak Tenguria
 */
public class SudokuLayout extends javax.swing.JFrame {
    public String sudokuBoard[][];
    public SudokuLayout(int sudokuSize, String[][] sudokuArray, String[][] sudokuBoard) {
        
        GridLayout grid = new GridLayout(sudokuSize,sudokuSize);
        JPanel panel = new JPanel();
        setSize(1000,1000);
        panel.setLayout(grid);
        
        int onePossibleCount = 0;
        OnePossibleSolution onePossibleSolution = new OnePossibleSolution(sudokuBoard);
        long startTime = System.nanoTime();
        onePossibleSolution.solveSudoku();
        long endTime = System.nanoTime();
        long totalTimeTaken1 = endTime - startTime;
        onePossibleSolution.display();
        onePossibleCount = onePossibleSolution.getOnePossibleSolutionCount();
        this.sudokuBoard = onePossibleSolution.getSudokuBoard();
        
        for (int i=1; i< sudokuSize+1; i++) {
            for (int j = 0; j < sudokuSize; j++) {
                panel.add(new JButton(sudokuBoard[i][j]));
            }
        }
        getContentPane().add(panel);
        
    }
    
    public String[][] getSudokuBoard(){
        return sudokuBoard;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
